name: rick_morty
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  build_runner: ^2.4.11
  dio: ^5.7.0
  get_it: ^8.0.1
  injectable: ^2.5.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: 2.6.2
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
